name: Task03Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: windows-latest

    permissions:
      repository-projects: write
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: nuGet create
      run: dotnet pack 
      working-directory: PowerCollections
    - name: nuGet publish
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Anton7662/index.json --skip-duplicate
      working-directory: PowerCollections\PowerCollections\bin\Debug\
      
    - name: XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'PowerCollections\PowerCollections\PowerCollections.csproj'
        xpath: '//Version'

    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: 'v${{ steps.getxml.outputs.info }}'
