name: Task03Release1

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: windows-latest

    permissions:
      
      repository-projects: write
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: nuGet create
      run: dotnet pack 
      working-directory: PowerCollections
    - name: nuGet publish
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/Anton7662/index.json --skip-duplicate
      working-directory: PowerCollections\PowerCollections\bin\Debug\
      
    - name: XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: 'PowerCollections\PowerCollections\PowerCollections.csproj'
        xpath: '//Version'

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: 'v${{ steps.getxml.outputs.info }}'
        release_name: 'Release v${{ steps.getxml.outputs.info }}'
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

